server {
    listen 80;
    server_tokens off;
    server_name tintahub.es www.tintahub.es localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Medida — Logs de acceso
    access_log /var/log/nginx/tintahub_access.log;
    error_log /var/log/nginx/tintahub_error.log;

    # Medida — Cabeceras de seguridad HTTP
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' https: data: 'unsafe-inline'" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Medida — Limitar tamaño de peticiones
    client_max_body_size 10M;
    client_body_timeout 12;
    client_header_timeout 12;
    keepalive_timeout 15;
    send_timeout 10;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass         http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}