name: Deploy TintaHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Ubuntu Server
    runs-on: self-hosted

    steps:

      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Actualizar proyecto
        run: |
          cd /home/tintahub/tintahub
          git pull origin main

      - name: Reiniciar contenedores Docker
        run: |
          cd /home/tintahub/tintahub
          docker compose down
          docker compose up -d

      - name: Verificar despliegue
        run: |
          sleep 5
          docker ps
          curl -s http://localhost/test-db